In [1]:
pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 6.7 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.6 MB 7.0 MB/s eta 0:00:02
   -------------- ------------------------- 4.7/12.6 MB 7.7 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 7.9 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 8.0 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 8.2 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 8.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 8.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [3]:
mylist =[1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
myarr=np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

np.ones(5)

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.linspace(0,10,2)

array([ 0., 10.])

In [26]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [28]:
len(np.linspace(0,10,2))

2

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(1)

array([0.03941702])

In [32]:
np.random.rand(5,6)

array([[0.76543071, 0.04375845, 0.17769982, 0.30811353, 0.90441539,
        0.7768433 ],
       [0.37417237, 0.73657479, 0.00962844, 0.21078185, 0.42847124,
        0.06933003],
       [0.25605471, 0.27032342, 0.70493291, 0.8004687 , 0.62121009,
        0.22327911],
       [0.73338104, 0.72249037, 0.13335599, 0.61459555, 0.93530549,
        0.05309768],
       [0.33548406, 0.77955729, 0.75794813, 0.59223771, 0.68112697,
        0.2109859 ]])

In [33]:
np.random.randn(10)

array([ 1.32141861,  1.61000399, -0.47491112,  0.48421687, -1.85090246,
       -0.04873702, -0.37282467,  0.75861451,  0.20431507,  1.63414139])

In [34]:
np.random.randn(2,3)

array([[-0.6588512 , -0.01926155,  0.197934  ],
       [ 0.37258002,  0.02680783,  0.75775159]])

In [36]:
np.random.randint(0,101,(4,5))

array([[35,  3,  7,  6, 99],
       [81, 12, 27, 17, 55],
       [51,  9, 12, 63, 38],
       [31, 95, 59, 33, 29]], dtype=int32)

In [38]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [39]:
arr=np.arange(0,25)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr=np.random.randint(0,101,10)

In [42]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52], dtype=int32)

In [43]:
ranarr.max()

np.int32(99)

In [44]:
ranarr.min()

np.int32(2)

In [45]:
ranarr.argmax()

np.int64(5)

In [46]:
ranarr.argmin()

np.int64(7)

In [47]:
ranarr.dtype

dtype('int32')

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.shape

(25,)

In [50]:
arr=arr.reshape(5,5)

In [51]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
arr.shape

(5, 5)

In [53]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [54]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])